### ISSUE TITLE
show all calving times that meet the threshold on PDF

### ISSUE THREAD

**Issue by sarahcd** [nilanjanchatterjee/parturition#14]
Currently only the longest period meeting the threshold conditions are displayed on the PDF plot, but this is often not the correct or most visually obvious parturition time. All records for periods meeting the conditions are already identified by the analysis results and added to the RDS output. We'll add display of all thresholds that meet the conditions to the PDF plots.

Questions: 
How to allow users to compare which points on the map correspond with which dates?
How to display the parturition time? There is not enough room to list more than a few on the lefthand plot. It might help to truncate the display to just the date (remove time). Or could list them outside the plots.

**Comment by nilanjanchatterjee** [comment]
The updated version has the information for both the _.csv_ output and _plot_ has all the slowing down times
