### ISSUE TITLE
trackId stored as animal ID in artifacts

### ISSUE THREAD

**Issue by sarahcd** [nilanjanchatterjee/parturition#3]
Both Parturition_vel and Parturition_output show the trackId but not the animal IDs (i.e., individual_local_identifier). Both are stored correctly in the .rds output. Suggestions:
* Parturition_output.csv: rename Individual_id to trackId and add column individual_local_identifier or animal_id (@andreakoelzsch what is preferred?)
* Parturition_vel.pdf: This one is harder. The simplest solution might be to reduce font size and include both at the top of each graph.

The animal ID is critical to linking data back to individual animals and addressing sample sizes and repeated parturition events per individual. The trackId is important to include because it allows the App to report multiple parturition events, depending on how the data are prepared in prior workflow steps. For example, if I use _Filter Data by Season_, it will provide _Parturition_ with animal IDs as well as trackIds that identify track segments for each animal-year with available data. The trackIds are named by prior apps by appending a sequential number to the animal ID (e.g., three track segments for animal 100 will be named 1001, 1002, 1003). If the animal ID is not also included, this is very tricky to identify and resolve afterward.

**Comment by andreakoelzsch** [comment]
Hi all. To make things easier on the R side, the preferred names are trackId and individual.local.identifier. Thanks!

**Comment by nilanjanchatterjee** [comment]
In the recent app update, I have included another column in the .csv with the individual_id column to match the track_id with the individual_id...I can change the title of the pdf plot also and include both the track id and individual_id
